package com.chuanwise.xiaoming.minecraft.pack;

public enum PackType {
    UNKNOWN,

    HEARTBEAT_REQUEST,
    HEARTBEAT_ALIVE,

    MC_ERROR,
    XM_ERROR,

    MC_LOGGER,

    MC_DISCONNECT,
    XM_DISCONNECT,

    XM_BROADCAST_MESSAGE,

    XM_WORLD_NAME,
    MC_WORLD_NAME_RESULT,

    MC_SEND_GROUP_MESSAGE,
    MC_SEND_PRIVATE_MESSAGE,
    XM_SEND_MESSAGE_RESULT,

    XM_GET_BINDED_QQ_RESULT,
    MC_GET_BINDED_QQ,
    MC_GET_ALIAS_OR_CODE,
    XM_GET_ALIAS_OR_CODE_RESULT,

    XM_PLAYER_CONFIRM,
    XM_PLAYER_ACCEPT,
    MC_PLAYER_ACCET_RESULT,
    MC_PLAYER_CONFIRM_RESULT,

    XM_COMMAND,
    MC_COMMAND_RESULT,
    MC_COMMAND,
    XM_COMMAND_RESULT,

    MC_FLUSH_WORLD,
    MC_FLUSH,

    MC_ADD_SERVER_TAG,
    XM_ADD_SERVER_TAG_RESULT,
    MC_REMOVE_SERVER_TAG,
    XM_REMOVE_SERVER_TAG_RESULT,
    MC_LIST_SERVER_TAG,
    XM_LIST_SERVER_TAG_RESULT,

    MC_LIST_WORLD,
    XM_LIST_WORLD_RESULT,

    MC_ADD_WORLD_TAG,
    XM_ADD_WORLD_TAG_RESULT,
    MC_REMOVE_WORLD_TAG,
    XM_REMOVE_WORLD_TAG_RESULT,
    MC_LIST_WORLD_TAG,
    XM_LIST_WORLD_TAG_RESULT,


    XM_SEND_WORLD_MESSAGE,
    MC_SEND_WORLD_MESSAGE_RESULT,

    MC_SEND_TITLE_RESULT,
    XM_CHECK_ONLINE,
    MC_CHECK_ONLINE_RESULT,

    MC_SEND_MESSAGE_RESULT,

    MC_BIND,
    XM_BIND_RESULT,

    MC_UNBIND,
    XM_UNBIND_RESULT,

    MC_PLAYER_JOIN,
    MC_PLAYER_EXIT,

    XM_SEND_MESSAGE,
    XM_SEND_MESSAGE_TO_ALL_PLAYERS,
    XM_SEND_TITLE,
    XM_SEND_TITLE_TO_ALL_PLAYERS,

    MC_APPLY_COMMAND,
    XM_APPLY_COMMAND_RESULT,

    XM_ONLINE_PLAYER,
    MC_ONLINE_PLAYER_RESULT,

    XM_HAS_PERMISSION,
    MC_HAS_PERMISSION_RESULT,

    XM_HAS_WORLD,
    MC_HAS_WORLD_RESULT,

    MC_PLAYER_CHAT,
    XM_PLAYER_CHAT_RESULT,

    MC_CONNECT,
    MC_REQUIRE_XM_IDENTIFY,
    XM_REQUIRE_ORIGINAL_IDENTIFY,
    XM_REQUIRE_MC_ENCRYPTED_IDENTIFY,

    MC_ENCRYPTED_IDENTIFY,
    MC_IDENTIFY,

    XM_ACCEPT_ENCRYPTED_IDENTIFY,
    MC_ACCEPT_ENCRYPTED_IDENTIFY,
    MC_DENY_ENCRYPTED_IDENTIFY,

    XM_ACCEPT_IDENTIFY,
    XM_DENY_IDENTIFY,
}
