name: 'xiaoming'
version: '1.1'
author: 'Chuanwise'
main: 'com.chuanwise.xiaoming.minecraft.bukkit.XiaomingBukkitPlugin'

commands:
  xiaoming:
    aliases:
      - xm
    usage: '§7[§6小明§7] §f小明不理解你的意思，可以使用 §e/xm help§f 查看帮助文档'
  xiaomingconfirm:
    aliases:
      - xmconfirm
    usage: '§7[§6小明§7] §f小明不理解你的意思，可以使用 §e/xm help§f 查看帮助文档'
  xiaomingaccept:
    aliases:
      - xmaccept
    usage: '§7[§6小明§7] §f小明不理解你的意思，可以使用 §e/xm help§f 查看帮助文档'
  xiaomingcancel:
    aliases:
      - xmcancel
    usage: '§7[§6小明§7] §f小明不理解你的意思，可以使用 §e/xm help§f 查看帮助文档'
  xiaomingdeny:
    aliases:
      - xmdeny
    usage: '§7[§6小明§7] §f小明不理解你的意思，可以使用 §e/xm help§f 查看帮助文档'
  xiaomingexecute:
    aliases:
      - xmexe
      - xmexecute
    usage: '§7[§6小明§7] §f小明不理解你的意思，可以使用 §e/xm help§f 查看帮助文档'
  xiaomingsend:
    aliases:
      - xmsend
    usage: '§7[§6小明§7] §c用法：§e/xmsend [频道消息]§f'
  menu: {}